<?php

/**
 * @file
 * Contains views_arg_entity_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function views_arg_entity_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the views_arg_entity_field module.
    case 'help.page.views_arg_entity_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Views argument_default plugin to pull values of the &#039;&#039;Current&#039;&#039; entity&#039;&#039;s fields') . '</p>';
      return $output;

    default:
  }
}
