field.widget.settings.tagify_entity_reference_autocomplete_widget:
  type: field.widget.settings.tagify
  label: 'Tagify entity reference widget'
  mapping:
    match_operator:
      type: string
      label: 'Autocomplete matching'
    match_limit:
      type: integer
      label: 'Maximum number of autocomplete suggestions.'
    suggestions_dropdown:
      type: integer
      label: 'Suggestions dropdown.'
    placeholder:
      type: string
      label: 'Placeholder'
