<?php

use Drupal\Core\Entity\EntityPublishedInterface;

function tagify_user_list_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $a = $form_id;
  $ba = $form_id;
}

/**
 * Implements hook_select2_autocomplete_matches_alter().
 */
function tagify_user_list_tagify_user_list_autocomplete_matches_alter(array &$matches, array $options) {
  $entity_manager = \Drupal::entityTypeManager();

  $entities = $entity_manager->getStorage($options['target_type'])->loadMultiple(array_keys($matches));
}
