<?php

/**
 * @file
 * Provides integration with Bootstrap Multiselect library.
 */

/**
 * Implements hook_library_info_alter().
 */
function bootstrap_multiselect_library_info_alter(&$libraries, $module) {
  if ($module == 'bootstrap_multiselect') {
    // Use local library files rather than CDN if they're present.
    // @see https://www.drupal.org/node/3099614
    $library_file_finder = \Drupal::service('library.libraries_directory_file_finder');
    $current_libraries = [
      'js' => 'bootstrap_multiselect/js/bootstrap-multiselect.min.js',
      'css' => 'bootstrap_multiselect/css/bootstrap-multiselect.min.css',
    ];

    $path = $library_file_finder->find($current_libraries['js']);
    if ($path) {
      $libraries['multiselect']['js'] = [
        '/' . $path => ['minified' => TRUE, 'external' => FALSE]
      ];
    }
    $path = $library_file_finder->find($current_libraries['css']);
    if ($path) {
      $libraries['multiselect']['css'] = [
        'theme' => [
          '/' . $path => ['minified' => TRUE, 'external' => FALSE]
        ]
      ];
    }
  }
}
